apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "books-helm.fullname" . }}-destination
  labels:
    chart: {{ template "books-helm.chart" . }}
    release: {{ .Release.Name }}
spec:
  host: {{ include "books-helm.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: {{ .Values.api.version }}
    labels:
      version: {{ .Values.api.version }}